# Generated by Django 2.2.9 on 2019-12-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trench',
            name='images',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
