# Generated by Django 2.2.9 on 2019-12-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0002_trench_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='trench',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
