# Generated by Django 2.2.9 on 2019-12-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0003_trench_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='images',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='find',
            name='images',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='images',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
