# Generated by Django 2.2.9 on 2019-12-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0004_auto_20191228_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='images',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
