# Generated by Django 2.2.9 on 2019-12-31 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0006_auto_20191231_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find',
            name='inventory_number',
        ),
    ]
