# Generated by Django 2.2.9 on 2019-12-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0009_auto_20191231_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='excavation.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='find',
            name='finding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='excavation.Finding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='find',
            name='inventory_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='find',
            name='trench',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='excavation.Trench'),
            preserve_default=False,
        ),
    ]
