# Generated by Django 2.2.9 on 2019-12-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0015_auto_20191231_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find',
            name='inventory_number',
        ),
    ]
