# Generated by Django 2.2.9 on 2019-12-31 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0017_auto_20191231_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='inventory_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='find',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Area'),
        ),
        migrations.AlterField(
            model_name='find',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Finding'),
        ),
        migrations.AlterField(
            model_name='find',
            name='trench',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Trench'),
        ),
    ]
