# Generated by Django 2.2.9 on 2020-01-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0019_trench_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trench',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
