# Generated by Django 2.2.9 on 2020-01-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0020_auto_20200109_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trench',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
