# Generated by Django 2.2.9 on 2020-01-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0021_auto_20200110_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trench',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
