# Generated by Django 2.2.9 on 2020-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0022_auto_20200114_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=250)),
                ('editor', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
