# Generated by Django 2.2.9 on 2020-01-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0023_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='HomePage',
        ),
    ]
