# Generated by Django 2.2.9 on 2020-01-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0026_building_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
