# Generated by Django 2.2.9 on 2020-01-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0028_auto_20200115_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='slug',
        ),
    ]
