# Generated by Django 2.2.9 on 2020-01-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0030_building_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='slug',
        ),
    ]
