# Generated by Django 2.2.9 on 2020-01-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0032_building_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
