# Generated by Django 2.2.9 on 2020-01-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0033_auto_20200115_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='find',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='find',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='finding',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='finding',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trench',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trench',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('name', 'slug')},
        ),
    ]
