# Generated by Django 2.2.9 on 2020-01-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0034_auto_20200115_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
