# Generated by Django 2.2.9 on 2020-01-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0035_auto_20200115_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='date',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='find',
            old_name='date',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='finding',
            old_name='date',
            new_name='entry_date',
        ),
        migrations.AddField(
            model_name='building',
            name='archaeological_date',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='object',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='find',
            name='archaeological_date',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='find',
            name='editor',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='find',
            name='object',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='find',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='archaeological_date',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='excavation.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='depth',
            field=models.FloatField(default=0, help_text='m'),
        ),
        migrations.AddField(
            model_name='finding',
            name='editor',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='object',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(help_text='aÇiklama'),
        ),
        migrations.AlterField(
            model_name='area',
            name='images',
            field=models.ImageField(help_text='Görüntüler', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='Ad', max_length=250),
        ),
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='depth',
            field=models.FloatField(default=0, help_text='m'),
        ),
        migrations.AlterField(
            model_name='building',
            name='height',
            field=models.FloatField(default=0, help_text='m'),
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='building',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='width',
            field=models.FloatField(default=0, help_text='m'),
        ),
        migrations.AlterField(
            model_name='find',
            name='depth',
            field=models.FloatField(default=0, help_text='m'),
        ),
        migrations.AlterField(
            model_name='find',
            name='diameter',
            field=models.FloatField(default=0, help_text='m'),
        ),
        migrations.AlterField(
            model_name='find',
            name='height',
            field=models.FloatField(default=0, help_text='m'),
        ),
        migrations.AlterField(
            model_name='find',
            name='inventory_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='find',
            name='width',
            field=models.FloatField(default=0, help_text='m'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='height',
            field=models.FloatField(default=0, help_text='m'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='finding',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='finding',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='width',
            field=models.FloatField(default=0, help_text='m'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='trench',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='trench',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
