# Generated by Django 2.2.9 on 2020-01-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0036_auto_20200117_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='find',
            old_name='inventory_number',
            new_name='name',
        ),
    ]
