# Generated by Django 2.2.9 on 2020-01-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0037_auto_20200117_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='short_description',
            field=models.CharField(default=1, help_text='Kısa Açıklama', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='short_description',
            field=models.CharField(default=1, help_text='Kısa Açıklama', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='find',
            name='building',
            field=models.ForeignKey(default=1, help_text='bina', on_delete=django.db.models.deletion.CASCADE, to='excavation.Building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='find',
            name='short_description',
            field=models.CharField(default=1, help_text='Kısa Açıklama', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='building',
            field=models.ForeignKey(default=1, help_text='bina', on_delete=django.db.models.deletion.CASCADE, to='excavation.Building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='short_description',
            field=models.CharField(default=1, help_text='Kısa Açıklama', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='trench',
            field=models.ForeignKey(default=1, help_text='hendek', on_delete=django.db.models.deletion.CASCADE, to='excavation.Trench'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trench',
            name='short_description',
            field=models.CharField(default=1, help_text='Kısa Açıklama', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='archaeological_date',
            field=models.CharField(help_text='arkeolojik tarih', max_length=250),
        ),
        migrations.AlterField(
            model_name='building',
            name='area',
            field=models.ForeignKey(help_text='alan', on_delete=django.db.models.deletion.CASCADE, to='excavation.Area'),
        ),
        migrations.AlterField(
            model_name='building',
            name='depth',
            field=models.FloatField(default=0, help_text='derinlik/m'),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(help_text='aÇiklama'),
        ),
        migrations.AlterField(
            model_name='building',
            name='editor',
            field=models.CharField(help_text='editör', max_length=250),
        ),
        migrations.AlterField(
            model_name='building',
            name='entry_date',
            field=models.DateTimeField(help_text='giriş tarihi'),
        ),
        migrations.AlterField(
            model_name='building',
            name='height',
            field=models.FloatField(default=0, help_text='sekiz/m'),
        ),
        migrations.AlterField(
            model_name='building',
            name='images',
            field=models.ImageField(help_text='Görüntüler', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, help_text='enlem', max_digits=18),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, help_text='boylam', max_digits=18),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(help_text='Ad', max_length=250),
        ),
        migrations.AlterField(
            model_name='building',
            name='object',
            field=models.CharField(help_text='nesne', max_length=250),
        ),
        migrations.AlterField(
            model_name='building',
            name='width',
            field=models.FloatField(default=0, help_text='genişlik/m'),
        ),
        migrations.AlterField(
            model_name='find',
            name='archaeological_date',
            field=models.CharField(help_text='arkeolojik tarih', max_length=250),
        ),
        migrations.AlterField(
            model_name='find',
            name='area',
            field=models.ForeignKey(help_text='alan', on_delete=django.db.models.deletion.CASCADE, to='excavation.Area'),
        ),
        migrations.AlterField(
            model_name='find',
            name='depository',
            field=models.CharField(help_text='emanetçi', max_length=250),
        ),
        migrations.AlterField(
            model_name='find',
            name='depth',
            field=models.FloatField(default=0, help_text='derinlik/m'),
        ),
        migrations.AlterField(
            model_name='find',
            name='description',
            field=models.TextField(help_text='aÇiklama'),
        ),
        migrations.AlterField(
            model_name='find',
            name='diameter',
            field=models.FloatField(default=0, help_text='çap/m'),
        ),
        migrations.AlterField(
            model_name='find',
            name='editor',
            field=models.CharField(help_text='editör', max_length=250),
        ),
        migrations.AlterField(
            model_name='find',
            name='entry_date',
            field=models.DateTimeField(help_text='giriş tarihi'),
        ),
        migrations.AlterField(
            model_name='find',
            name='finding',
            field=models.ForeignKey(help_text='bulgu', on_delete=django.db.models.deletion.CASCADE, to='excavation.Finding'),
        ),
        migrations.AlterField(
            model_name='find',
            name='height',
            field=models.FloatField(default=0, help_text='sekiz/m'),
        ),
        migrations.AlterField(
            model_name='find',
            name='images',
            field=models.ImageField(help_text='Görüntüler', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='find',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, help_text='enlem', max_digits=18),
        ),
        migrations.AlterField(
            model_name='find',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, help_text='boylam', max_digits=18),
        ),
        migrations.AlterField(
            model_name='find',
            name='material',
            field=models.CharField(help_text='malzeme', max_length=250),
        ),
        migrations.AlterField(
            model_name='find',
            name='name',
            field=models.CharField(help_text='Ad', max_length=250),
        ),
        migrations.AlterField(
            model_name='find',
            name='object',
            field=models.CharField(help_text='nesne', max_length=250),
        ),
        migrations.AlterField(
            model_name='find',
            name='trench',
            field=models.ForeignKey(help_text='hendek', on_delete=django.db.models.deletion.CASCADE, to='excavation.Trench'),
        ),
        migrations.AlterField(
            model_name='find',
            name='width',
            field=models.FloatField(default=0, help_text='genişlik/m'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='archaeological_date',
            field=models.CharField(help_text='arkeolojik tarih', max_length=250),
        ),
        migrations.AlterField(
            model_name='finding',
            name='area',
            field=models.ForeignKey(help_text='alan', on_delete=django.db.models.deletion.CASCADE, to='excavation.Area'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='depth',
            field=models.FloatField(default=0, help_text='derinlik/m'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=models.TextField(help_text='aÇiklama'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='editor',
            field=models.CharField(help_text='editör', max_length=250),
        ),
        migrations.AlterField(
            model_name='finding',
            name='entry_date',
            field=models.DateTimeField(help_text='giriş tarihi'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='height',
            field=models.FloatField(default=0, help_text='sekiz/m'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='images',
            field=models.ImageField(help_text='Görüntüler', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, help_text='enlem', max_digits=18),
        ),
        migrations.AlterField(
            model_name='finding',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, help_text='boylam', max_digits=18),
        ),
        migrations.AlterField(
            model_name='finding',
            name='name',
            field=models.CharField(help_text='Ad', max_length=250),
        ),
        migrations.AlterField(
            model_name='finding',
            name='object',
            field=models.CharField(help_text='nesne', max_length=250),
        ),
        migrations.AlterField(
            model_name='finding',
            name='width',
            field=models.FloatField(default=0, help_text='genişlik/m'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='area',
            field=models.ForeignKey(help_text='alan', on_delete=django.db.models.deletion.CASCADE, to='excavation.Area'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='description',
            field=models.TextField(help_text='aÇiklama'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='editor',
            field=models.CharField(help_text='editör', max_length=250),
        ),
        migrations.AlterField(
            model_name='trench',
            name='images',
            field=models.ImageField(help_text='Görüntüler', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, help_text='enlem', max_digits=18),
        ),
        migrations.AlterField(
            model_name='trench',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, help_text='boylam', max_digits=18),
        ),
        migrations.AlterField(
            model_name='trench',
            name='name',
            field=models.CharField(help_text='Ad', max_length=250),
        ),
    ]
