# Generated by Django 2.2.9 on 2020-01-17 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0039_auto_20200117_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='trench',
            field=models.ForeignKey(default='NONE', editable=False, help_text='hendek', on_delete=django.db.models.deletion.CASCADE, to='excavation.Trench'),
        ),
    ]
