# Generated by Django 2.2.9 on 2020-01-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0040_auto_20200117_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='trench',
            field=models.ForeignKey(blank=True, help_text='hendek', null=True, on_delete=django.db.models.deletion.CASCADE, to='excavation.Trench'),
        ),
    ]
