# Generated by Django 2.2.9 on 2020-01-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0041_auto_20200117_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='building',
            field=models.ForeignKey(blank=True, help_text='bina', null=True, on_delete=django.db.models.deletion.CASCADE, to='excavation.Building'),
        ),
        migrations.AlterField(
            model_name='find',
            name='finding',
            field=models.ForeignKey(blank=True, help_text='bulgu', null=True, on_delete=django.db.models.deletion.CASCADE, to='excavation.Finding'),
        ),
        migrations.AlterField(
            model_name='find',
            name='trench',
            field=models.ForeignKey(blank=True, help_text='hendek', null=True, on_delete=django.db.models.deletion.CASCADE, to='excavation.Trench'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='building',
            field=models.ForeignKey(blank=True, help_text='bina', null=True, on_delete=django.db.models.deletion.CASCADE, to='excavation.Building'),
        ),
    ]
