# Generated by Django 2.2.9 on 2020-01-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0044_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ad', max_length=250)),
                ('editor', models.CharField(help_text='editör', max_length=250)),
                ('images', models.ImageField(help_text='Görüntüler', upload_to='pics')),
                ('short_description', models.CharField(help_text='Kısa Açıklama', max_length=250)),
                ('description', models.TextField(help_text='aÇiklama')),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
